# This is an FortiGate configuration example with two Geneve tunnel: geneve-az1, geneve-az2. Please add or remove based on your own value.
# Geneve tunnel name will be with format 'geneve-az<NUMBER>'. Check 'az_name_map' of the output of template, which is map of Geneve tunnel name to the AZ name that supported in Security VPC.

config router static
    edit 0
        set distance 5
        set priority 100
        set device "geneve-az1"
    next
    edit 0
        set distance 5
        set priority 100
        set device "geneve-az2"
    next
end


config router policy
    edit 1
        set input-device "geneve-az1"
        set output-device "geneve-az1"
    next
    edit 2
        set input-device "geneve-az2"
        set output-device "geneve-az2"
    next
end

config firewall policy
    edit 0
        set name "internal"
        set srcintf "geneve-az1" "geneve-az2"
        set dstintf "geneve-az1" "geneve-az2"
        set action accept
        set srcaddr "all"
        set dstaddr "all"
        set schedule "always"
        set service "ALL"
    next
end